<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Undefined variable $mysqliAdmin in C:\wamp64\www\esamagri\api\important_functions.php on line <i>83</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0221</td><td bgcolor='#eeeeec' align='right'>448432</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\esamagri\api\save_signup_info.php' bgcolor='#eeeeec'>...\save_signup_info.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0224</td><td bgcolor='#eeeeec' align='right'>531000</td><td bgcolor='#eeeeec'>create_user( <span>$name = </span><span>&#39;kundan jha&#39;</span>, <span>$num = </span><span>&#39;8013961194&#39;</span>, <span>$email = </span><span>&#39;k@gmail.com&#39;</span> )</td><td title='C:\wamp64\www\esamagri\api\save_signup_info.php' bgcolor='#eeeeec'>...\save_signup_info.php<b>:</b>10</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: Call to a member function close() on null in C:\wamp64\www\esamagri\api\important_functions.php on line <i>83</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: Call to a member function close() on null in C:\wamp64\www\esamagri\api\important_functions.php on line <i>83</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0221</td><td bgcolor='#eeeeec' align='right'>448432</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\esamagri\api\save_signup_info.php' bgcolor='#eeeeec'>...\save_signup_info.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0224</td><td bgcolor='#eeeeec' align='right'>531000</td><td bgcolor='#eeeeec'>create_user( <span>$name = </span><span>&#39;kundan jha&#39;</span>, <span>$num = </span><span>&#39;8013961194&#39;</span>, <span>$email = </span><span>&#39;k@gmail.com&#39;</span> )</td><td title='C:\wamp64\www\esamagri\api\save_signup_info.php' bgcolor='#eeeeec'>...\save_signup_info.php<b>:</b>10</td></tr>
</table></font>